global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'redes2-monitor'
    aluno: 'Rayssa Alves'
    matricula: '20239019558'


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'nginx'
    static_configs:
      - targets: ['95.58.0.3:9113']
        labels:
          servidor: 'nginx'
          tipo: 'servidor_web'
          
  - job_name: 'apache'
    static_configs:
      - targets: ['95.58.0.5:9117']
        labels:
          servidor: 'apache'
          tipo: 'servidor_web'

  - job_name: 'nginx_node'
    static_configs:
      - targets: ['95.58.0.2:9100']   # Porta exposta no docker-compose
        labels:
          servidor: 'nginx'
          tipo: 'recursos_container'

  # ============================
  # ðŸ”¥ APACHE - NODE EXPORTER
  # ============================
  - job_name: 'apache_node'
    static_configs:
      - targets: ['95.58.0.4:9100']
        labels:
          servidor: 'apache'
          tipo: 'recursos_container'

  
